tipo = input('Digite Algo: ')
print('O tipo primitivo desse valo é {}!'.format(type(tipo)))
print('Só tem espaços?'.format(tipo.isspace()))
print('É um número? {}!'.format(tipo.isnumeric()))
print('É alfabético? {}!'.format(tipo.isalpha()))
print('É alfabumérico? {}!'.format(tipo.isalnum()))
print('Está em maiúsculo? {}!'.format(tipo.isupper()))
print('Está em minúsculo? {}!'.format(tipo.islower()))
print('Está capitalizado? {}!'.format(tipo.istitle()))
