m = float(input('Digite um valor em metros: '))
print('{}Km'.format(m / 1000))
print('{}hm'.format(m / 100))
print('{}dam'.format(m / 10))
print('{}m'.format(m))
print('{:.0f}dm'.format(m * 10))
print('{:.0f}cm'.format(m * 100))
print('{:.0f}mm'.format(m * 1000))
